# Generated by Django 2.2.7 on 2020-01-28 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='galery/images')),
                ('video', models.FileField(upload_to='galery/videos')),
                ('likes', models.IntegerField(default=0)),
                ('created_on', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mediafeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_media', to='gallery.Media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
