# Generated by Django 2.2.7 on 2020-01-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.FileField(blank=True, upload_to='galery/images'),
        ),
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, upload_to='galery/videos'),
        ),
    ]
