# Generated by Django 2.2.7 on 2020-01-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='file',
        ),
        migrations.AddField(
            model_name='postmedia',
            name='image',
            field=models.FileField(blank=True, upload_to='post_medias/images'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='video',
            field=models.FileField(blank=True, upload_to='post_medias/videos'),
        ),
    ]
