# Generated by Django 2.2.7 on 2020-01-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200127_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='poster',
            field=models.FileField(blank=True, upload_to='post_medias/videos/poster'),
        ),
    ]
